project:
  type: book
  output-dir: docs

book:
  title: "Second year progress review"
  author:
  - name: Nicholas Harbour
    orcid: 0009-0008-2424-4516
    corresponding: true
    email: nicholas.harbour@nottingham.ac.uk
    roles: []
    affiliations:
      - "Centre for Mathematical Medicine and Biology, School of Mathematical Sciences, University of Nottingham, Nottingham, NG7 2RD, UK"
  date: today
  chapters:
    - index.qmd
    - summary.qmd
    - Lit_review.qmd
    - preprint.qmd
    - references.qmd
  page-navigation: true
  cover-image: cover.png
  downloads: [pdf, docx]
  page-footer:
    left: |
      Nicholas Harbour Second year progress review
    right: |
      This book was built with <a href="https://quarto.org/">Quarto</a>.
  repo-url: https://github.com/Harbour-N/Second-year-report
  repo-actions: [edit, issue]



bibliography: references.bib

supervisors:
  - name: Markus Owen
  - name: Matthew Hubbard


format:
  html:
    theme: cosmo
  pdf: 
    theme: default
    link-citations: true
    margin-left: 2cm
    margin-right: 2cm
    margin-top: 3cm
    margin-bottom: 3cm
    keep-tex: true
    template-partials:
      - before-body.tex


  docx: default


comments:
  hypothesis: true
