# Summary

This chapter provides an overview of the progress in my PhD research and outlines the future direction of my thesis.

My PhD research centres on the mathematical modelling of cellular subpopulations in glioblastoma (GBM), the most common and aggressive primary malignant brain caner in adults. During the first year, I focused on analysing single-cell and bulk RNA-seq data, aiming to extract dynamic information about tumour progression from these static snapshots, to motivate mathematical modelling. This lead to many conference talks/posters and a published abstract [Inference of cell cycle regulation between glioblastoma subpopulations in vivo to drive computational and mathematical models of the cancer complex system](https://doi.org/10.1093/neuonc/noad179.0150) from the Society of Neuro-Oncology annual meeting, although it may not form a significant part of my thesis.  

Following my initial visit to the Mathematical Neuro-Oncology Lab, run by Kristin Swanson at the Mayo Clinic in May 2023, I became involved in a project investigating differentiation therapy as a novel treatment for GBM, this is a joint project  with Dr Quinones lab in the department of Neurosurgery (Mayo Clinic Florida). 
This has become the primary focus of my second year. 
GBM remains almost universally fatal, partly due to its resistance to radiation therapy. 
Research has identified a subpopulation of cancer cells in GBM (and other cancers) with stem cell-like properties that make them highly resistant to conventional cytotoxic treatments, such as radiotherapy and chemotherapy. 
These cancer stem cells (CSCs), or glioma stem cells (GSC) in the case of glioma, are believed to drive tumour initiation, growth, and recurrence, making their eradication crucial for effective treatment. 
Dr Quinones' lab is developing new therapies for GBM using novel delivery mechanisms that aim to create a less favourable microenvironment for GBM to survive. 
One therapy they are particularly interested in is BMP4; this is a protein that has been shown to drive differentiation of GSCs towards a predominantly glial (astrocytic) fate, to reduce GBM tumor burden *in vivo* and to improve survival in a mouse model of GBM. 
Throughout my second year, we have been developing a mathematical model that simulates GSC-driven tumor growth in GBM, its response to BMP4 therapy and standard radiotherapy. 
Using data from five glioma stem cell lines provided by Dr. Quinones' lab, we have parameterized this model, enabling us to estimate the sensitivity of these cell lines to BMP4. 
We explore the model for a range of different parameters developing a virtual clinical trial approach to see how BMP4 impacts simulated GBM growth across a range of virtual cohorts. 
Our findings suggest that tumour proliferation rate is also a critical factor that must be accounted for when assessing BMP4 efficacy. 
Additionally, we have used this model to explore various BMP4 treatment schedules, with the ultimate goal of informing future clinical trial design.

In addition to this primary project, I have been involved in several other initiatives during my second year, which are not detailed anywhere else in this report.
In November 2023 I took part in the Integrated Mathematical Oncology (IMO) workshop at the Moffit Cancer Center, Florida. 
Our team developed a mathematical model for evolutionary steering in breast cancer, came second place and won a pilot fund of $50,000 to further this research project (<https://imoworkshop.org/IMO11/index.html>). 
In March 2024, I undertook a second visit to the Mathematical Neuro-Oncology Lab at Mayo Clinic Arizona. During this visit I took part in an academic retreat focusing on sex differences and the the immune landscape in GBM. 
This visit strengthened my collaboration with the group, resulting in an official research internship position.
From May to June I led a team of PhD students and research staff in a [datathon]( (<https://wolfbyttner.github.io/exeter-quantitative-modelling/>)) run by the University of Exeter and EPSRC Hub for Quantitative Modelling in Healthcare. 
The goal was to quantify heterogeneity in human daily rhythms using time series data of hormone concentrations in healthy individuals. Our team won the prize for best negative result, using functional data analysis and machine learning techniques to demonstrate that circadian rhythm signals from sleep-wake cycles dominate over other signals that could differentiate patient metadata such as sex, age or weight.

The plan for my thesis includes several chapters based on a series of papers, a draft of the anticipated structure is as follows:

- **Introduction**: A short text explaining the context and structure of the thesis.

- **Outreach paper**:  We aim to publish a paper in Frontiers for Young Minds, a journal targeting a young audience (ages 9-15). This could serve as an engaging and non-traditional introductory chapter to my thesis, explaining the basics of modelling in GBM.

- **Literature review**: An overall literature review, encompassing all of my work. This will be slightly broader than the literature review presented in this report (@sec-lit-review) that focuses specifically on the cancer stem cell literature that is particularly useful for understanding the context for my preprint.

- **BMP4 Virtual Clinical Trials**: This will be based on the preprint [Virtual Clinical Trials of BMP4 Differentiation Therapy: Digital Twins to Aid Glioblastoma Trial Design](https://www.biorxiv.org/content/10.1101/2024.08.22.609156v1.abstract). We plan to submit this to a broad interdisciplinary science journal, focusing on the integration of data and modelling, as well as model-informed clinical trial design.

- **Mathematical Analysis of the model**: Following on from this we are planing on writing a paper that will consider the model from a more mathematical perspective. We have already begun some of this analysis such as steady states of the model, nullclines, model reductions, although this analysis is not included in this report. 

- **Digital Twins and Alan Turing Institute**: Beginning in January 2025, I will participate in the Alan Turing Institute's PhD enrichment placement, which is designed to help PhD students deepen their research in machine learning and data science. The Institute hosts a center dedicated to digital twin research, where I plan to tackle some of the fundamental challenges in developing digital twins for healthcare, such as creating robust, uncertainty-aware models that can be effectively used in clinical settings. In collaboration with the Mathematical Neuro-Oncology Lab, we will apply these ideas to digital twin models for GBM.

- **Conclusion**: Drawing together the strands of the thesis.